version: "3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GO111MODULE=on
    volumes:
      - ./:/app
      - /home/zgaduj/go:/go
    ports:
    - 8088:8080
    working_dir: /app
    command: go run init/api.go
    depends_on:
      - db


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - GO111MODULE=on
    volumes:
      - ./:/app
      - /home/zgaduj/go:/go
    working_dir: /app
    command: go run init/worker.go
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
