version: "3"

services:

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - db.env
    environment:
      - GO111MODULE=on
      - APP_ENDPOINT_PORT=8080
      - APP_HTTP_MAX_BODY_SIZE=1024
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    working_dir: /app
    command: ["./scripts/wait-for-it.sh", "db:3306", "-t", "120", "--", "go", "run", "init/api/main.go"] # go run init/worker/main.go
  #    depends_on:
  #      - db


  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - db.env
    environment:
      - GO111MODULE=on
      - TIMEOUT_HTTP_REQUEST=5
      - INTERVAL_CHECK_URL=2
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./scripts/wait-for-it.sh", "db:3306", "-t", "120", "--", "go", "run", "init/worker/main.go"] # go run init/worker/main.go
  #    depends_on:
  #      - db

  db:
    image: mysql:5.7
    restart: always
#    ports:
#      - 3306:3306
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
